fossasia/gci18.fossasia.org

README.md
- Added basic contributing instructions as they should be a must-read for all participating students and mentors.
- Added link to Best Practices
=> Fixes #1  - Updated ReadMe.md

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Added PR and Issue Templates
Solves: #31
=> PR and Issue Templates

index.html
Removed Cart and Search Icon from Header.
Fixes #20 
Old Screenshot
New Screenshot
Preview Link
https://niteshkumarniranjan.github.io/gci18.fossasia.org/
=> Removed Cart and Search Icon

css/custom.css, index.html
Fixes #12 
- Created Social Media Section
- Added links to Facebook and Twitter with icons
- Linked YouTube
- Integrated a video that I made myself(hope you like it!)
[Preview Link](https://saarthakchats.github.io/ssasia.org/)
=> Fixes #12 : Created social media section

_includes/footer.html
- Fixes #28 
Removes Template Update Popup
=> Removes Template Update Popup (#28)

index.html
- Fixes #57 
Merged two student's section into one.
=> Merging two students section in one (#57)

_includes/footer.html, css/custom.css, index.html
- Fixes #58 
Merged two footers in one
=> Merge two footers in one (#58)

css/custom.css, index.html
- Fixes #27 
- Alignment in Mobile
- Changed Header from "Mentors Section" to "Our Mentors"
- Remove dummy template data
**Old Screenshot**
**New Screenshot**
=> Improve UX for Mentor Section (#27)

_includes/header.html, css/socialmedia-icons.css, index.html
- Fixes https://github.com/fossasia/gci18.fossasia.org/issues/71
- Preview Link: https://applec4t.github.io/gci18.fossasia.org/
Before:
After:
Expanded the social media section and added new css file for the icons.
=> Expanded the social media section and added a css file for icons (#71)

_includes/footer.html, _includes/header.html, css/custom.css, css/thankyou.scss, index.html, index.pug, js/thankyou.js
- Fixes #104
-  [Preview](https://saarthakchats.github.io/alby/)
- Added Thank you for contributing section
- Added typewriter JS effect
- Added in English
- Added in French
=> Added Thank you section with Js effect

css/custom.css, index.html
- Fixes #123 
- [Preview Link](https://saarthakchats.github.io/gc/)
Added relevant buttons with links
=> Fixes #123 : Enhanced contributors' section with more buttons and links

_includes/header.html
- Fixes 118
Add Student Projects Page Link  in NavBar
=> Add Student Projects Page Link (#118)

_includes/footer.html, index.html
- Fixes #129 
- [Preview Link](https://saarthakchats.github.io/gci18.fossasia.orglo/)
- Added Linkedin
- Added Flickr
- Added Google Plus
- Added these links to social section and also footer
- Removed unnecessary styles to make code more consistent and smaller
=> Added more social links

js/thankyou.js
- https://samyakbvs.github.io/gci18.fossasia.org/
Added Spanish Translation to Thankyou.js
=> Added Spanish Translation

js/thankyou.js
The Preview link is : https://jeewal.github.io/gci18.fossasia.org/
Added Nepali Translation of Thank You for your Contributions in Thankyou.js
=> Added Nepali Translation.

README.md
- Fixes #142 
- Preview Link
-
- Adding a mentor
- Adding Photo Nick
- Adding Language to Thank you Section
=> Fixes #142 : Documented adding a mentor, student and language

css/custom.css, index.html
=> Fixes Alignment of Student Section (#135)

css/custom.css, index.html, js/scripts.js
- Adds a link to the user's commits in the Contributors section
- Adds the user's name to the Contributors section
https://ryan10145.github.io/gci18.fossasia.org/
Fixes #148
=> Updated Contributors Section

_includes/footer.html, _includes/header.html, css/custom.css, index.html, js/backtotop.js
- Fixes #154 
- [Preview Link](https://saarthakchats.github.io/onlypartly/)
-
Added responsive back-to-top button on the website
=> Fixes #154 : Added Back to Top Button

js/scripts.js
- Github Pages Preview Link : https://sid911.github.io/gci18/
- Fixes #152 
-Added a native scrolling effect for moving in sections
Removed the snappy movement of moving to sections....
=> Added smooth scrolling effect Fixes #152

js/thankyou.js
[Preview Link](ammarbinfaisal.github.io/gci18)
I've added thank you for contributing in arabic as there was a gci task to add a translation of it in a language that is not present.
=> add arabic thank you

_includes/header.html
- Fixes `#67`
- Preview Link
Adds meta tags to header for better SEO and social media presence
=> GCI 2018: Add meta tags

README.md
- Fixed https://github.com/fossasia/gci18.fossasia.org/issues/140
- I added instructions to Run GCI'18 Website locally 
If you need to see from my repo. Here's the link - https://github.com/STEdirisuriya/gci18.fossasia.org/blob/master/README.md
@fragm3 I have resolved your issue.
Thank you!
=> [Fixed #140] Added instructions for run locally

js/thankyou.js
Added the Korean translation of Thank you
=> Added Korean translation of Thank you

css/theme.css, index.html
- https://stedirisuriya.github.io/gci18.fossasia.org/
- Make clear writings on the landing page
- https://github.com/fossasia/gci18.fossasia.org/issues/68
=> [Fixed #68] Make clear writings in the landing page

.gitignore
adding .vscode and .DS_Store to .gitignore
#178
=> #178 Update .gitignore

_includes/header.html, index.html
- Fixes #195 
- [Preview Link](https://saarthakchats.github.io/loky/)
- Added contributors section
- Added "Connect" section
=> Fixes #195 :Added Links to Navbar

js/scripts.js
- Fixes https://github.com/fossasia/gci18.fossasia.org/issues/197
- Preview Link: https://applec4t.github.io/gci18.fossasia.org/
Changed the target of the links in the conributors section to `_blank` so that they now open in a new tab instead of loading in the current tab, overloading on top of the main page.
=> (#197) Fixed the links in the contributors section

.github/PULL_REQUEST_TEMPLATE.md
- Fixes`#<Issue no.>`
- Preview Link
-
- Commented the parts which need to be read, but not shown
- Added more understandable explainations
- Added reference link for squashing
- Changed main branch to 'master'
- Added space for screenshots
- Hint for Preview Link
=> Improved PR template

css/custom.css, js/thankyou.js
- Change the colour of the animation matched to the theme
- Added the text in Sinhala
- https://stedirisuriya.github.io/gci18.fossasia.org/
- #205
=> [Fixed #205] Improved and added thank you for contributing text in Sinhala

README.md
- Fixes #173 
Added Communication section having gci18.fossasia.org gitter channel and fossasia google group in ReadMe.md file.
=> Update Readme.md with Communication Section

projects.html
- Preview: https://applec4t.github.io/gci18.fossasia.org/
- Fixes  https://github.com/fossasia/gci18.fossasia.org/issues/231
- Fixed the Jekyll script for generating links to student projects so that they now open in a new tab.
- Added a "back to the main page" button to the student project page enabling an intuitive way to load back the main page (previously it was only able by going back a page through the browser or clicking the FOSSASIA logo in the navbar which might have been unintuitive)
=> (#231) Added fixes to the student projects section

js/scripts.js
- [Preview Link](https://saarthakchats.github.io/hubis/)
- Fixes #166 
- Small change fixed the bug, now they are ordered properly
- ![](https://user-images.githubusercontent.com/24372680/47829267-83ca8080-ddac-11e8-98d2-87e10daa8f8c.png)
- <img width="1295" alt="screenshot 2018-11-05 at 11 34 12 pm" src="https://user-images.githubusercontent.com/24372680/48017080-5d616800-e153-11e8-9a6c-d34693ea2210.png">
- ![screenshot 2018-11-05 at 11 36 32 pm](https://user-images.githubusercontent.com/24372680/48017191-ac0f0200-e153-11e8-83f6-78ab5881159e.png)
=> (#166)Fixed Bug in Contributors' Section

css/custom.css, index.html, js/scripts.js
- [Preview Link](https://ryan10145.github.io/gci18.fossasia.org/)
- Fixes #241
Adds a listener to the map that only enables zooming when the map is clicked on. This allows the user to easily navigate the page without having to deal with scrolling into the map. Additionally, when the mouse is taken off of the map, the zooming is once again disabled.
=> Fixed Map Scrolling Issue

css/custom.css, index.html
- Added a embedded player that plays all of the videos from the Fossasia Youtube Channel
- Reorganized the social media links to use Bootstrap grid
- [Preview Link](https://ryan10145.github.io/gci18.fossasia.org/)
- Fixes #247 
=> Added Youtube to Social Media Section

css/custom.css
- [Preview Link](https://ammarbinfaisal.github.io/gci18)
- Fixes #218
The thankyou section of the website shrinks each time the typing animation occurs.  You can see that in [the present website](https://gci18.fossasia.org)'s thankyou section.  
This PR fixes that. check the fixed thankyou section here [here](https://ammarbinfaisal.github.io/gci18) 
This cant be showed in a gif screenshot
=> Fixes #218 Fix the Shrinking of Thank You section

css/custom.css, index.html
- [Preview Link](https://ryan10145.github.io/gci18.fossasia.org/)
- Fixes #239 
- Adds in an Instagram widget to the social media section that updates with the latest images from https://www.instagram.com/fossasia/?hl=en
=> Added Instagram Widget to Social Media Section

index.html
- [Preview Link](https://pythongiant.github.io/gci18.fossasia.org/)
- Fixes #259
Add link to slack channel on the social media section
=> Add slack icon

_includes/header.html, css/theme.css, index.html
- [Preview Link](https://pythongiant.github.io/gci18.fossasia.org/projects.html)
- Made #193 work
Makes the links in projects.html navbar work
=> fix projects.html navbar links

css/custom.css
- https://stedirisuriya.github.io/gci18.fossasia.org/
- Make map responsive 
- #229
=> [Fixed #229] Make map responsive 

_data/team.yml
preview link : https://subhahu123.github.io/foss1/
link before changes : https://gci18.fossasia.org/
link after changes : https://subhahu123.github.io/foss1/
change done in data/team file 
twitter and other details were interchanged ( Mario Behling . Hong Phuc Dang)
when we open their twitter account they are interchanged when click on mario behling twitter account it opens the Hong phuc dang twitter account or vice versa .
fixed issue : #304
=> bug fixing in team section

_data/mentors.yml
I added the location of a mentor: Rohit Potter.
https://stedirisuriya.github.io/gci18.fossasia.org/
=> Added location for a mentor

css/theme.css, index.html
- [Preview Link] https://sid911.github.io/gci18/
- Fixes #281 
Added a more responsive section instead of the old unresponsive one
=> Added a responsive memories section

css/theme.css, index.html
Fixed the squeezing of the fossasia projects
Added padding to the projects by adding`"padding-bottom: 25px"` to css 
fixes #295 
Preview Link : https://sid911.github.io/gci18/
=> Added padding to the Projects

README.md, _includes/header.html, css/theme-red.css, css/theme.css, index.html
- Changed the theme of the Website to red instead of green (current)
- Changed the theme of the nav to light (currently dark)
- Added gradients to the theme-red.css file
- Added description about Gradients in Readme.md 
-Github Pages Preview Link - https://sid911.github.io/gci18
- Added a new theme to the website, now the navbar is white themed instead of black and the main theme of the website is changed to red (the fossasia Color)
- Added gradients for further use
=> Changed the website theme and added gradients

js/thankyou.js
- [Compare changes](https://github.com/fossasia/gci18.fossasia.org/compare/master...phyyyl:master)
- Fixes #311 
I added the dutch translation for "thank you".
=> Dutch translation for  "thank you"

js/thankyou.js
- [Preview Link](https://sahilsaha7773.github.io/)
<!-- If you fully fixed some issue, please insert the issue number after the #.
I have added "Thank you for contributing" in Bengali language.
=> Added "Thank you for contributing"

_data/mentors.yml
- [Preview Link](https://pythongiant.github.io/gci18.fossasia.org/)
-  #96
added mentor Isuru Abeywardana
=> Add mentor

_includes/footer.html
Corrected the padding of the links in the footer  
- Fixes #217 
Removed extra closing divs so that container could close at right position.
=> Update footer design

js/thankyou.js
Description : Add a Thank You in Estonian Language
Link to the website : https://akshit15013.github.io/gci18.fossasia5.org/
Issue No. : #341
=> Add a Thank You

README.md, _data/orgprojects.yml, index.html
- [Preview Link]( https://pythongiant.github.io/gci18.fossasia.org/)
- Fixes #365 
Made fossasia projects section dynamic. now to add more fossasia's open source projects just edit the orgprojects.yml file
=> make fossasia projects section dynamic

js/thankyou.js
- [Preview Link](https://gaurang7goel.github.io/gci18.fossasia.org/.)
- Fixes https://github.com/fossasia/gci18.fossasia.org/issues/374
=> thank you in punjabi

index.html
- [Preview Link](https://sahilsaha7773.github.io/)
- Fixes #357 
I have added the smooth scrolling feature.
- Edited the index.html file to add smooth scrolling to all links.
=> Added smooth scrolling feature when clicked on Navbar elements

README.md
- Fixes #376
The steps in README were broken before. fixed them
=> fix steps to add mentors/projects

css/custom.css
- [Preview Link](https://saarthakchats.github.io/nba/#welcome)
- Fixes #382 
changed text look
=> Changed text look on team hover(#382)

js/thankyou.js
Added and Enhance "Thank you for contributing" in  Danish
- [Preview Link](url)
Added Danish translation for 'Thank you for your contributions!' in thankyou.js
=> added Danish language

js/thankyou.js
- [Preview Link](https://rahulaarora.github.io/gci18.fossasia.org/)
Added and Enhanced "Thank you for contributing!" with a nice JS effect in the Italian language to the FOSSASIA GCI website. 
=> Added and Enhanced "Thank you for contributing!"  in the Italian language

_data/team.yml
- [Preview Link](https://ryan10145.github.io/gci18.fossasia.org/)
- Fixes #413 
- Changes file extensions in team.yml so that the images in the Team section will load
=> Fix File Extensions for Team Images

css/custom.css, css/thankyou.scss
- [Preview Link](https://pythongiant.github.io/gci18.fossasia.org/)
- Fixes #422 
Animating the thank you section using CSS Keyframes
=> add animations to thank you section

index.html
- [Preview Link](https://sahilsaha7773.github.io/)
- Fixes #425 
The translate button was translating the team members' name to weird words. I fixed this error in this PR.
=> Fixed the translate feature

js/thankyou.js
- [Preview Link](https://jakubpawlina.github.io/gci18-fossasia/)
- Hungarian language added to the "Thank you" section
=> Hungarian language added

css/custom.css, index.html, js/scripts.js
- https://stedirisuriya.github.io/gci18.fossasia.org/
- Fixes #363 
- Added activities section with GitHub API.
=> Added activities section

js/thankyou.js
- [Preview Link](https://kualeyi.github.io/gci18.fossasia.org/)
This change places the Icelandic for 'Thank you for your contributions!' at the end of the thank-you animation.
_PR-ed as dxa_kly for Google Code-in 2018_
=> Updates thankyou.js with Icelandic

_includes/footer.html, css/custom.css, js/custom.js, students_projects.html
- [Preview Link](https://ksninja.github.io/temp/students_projects.html)
- Fixes #446 
Replaced the previous functionality of popovers with flip animation to show snapshot of project.
Clicking on the text flips the card and displays the image .
=> Improve Student Projects Section

css/custom.css
- Changed "View profile" button style according website theme
- [Preview Link](https://jakubpawlina.github.io/gci18-fossasia/)
I have changed the style of the button with the color from website theme <code>#e31d3b<span style="background-color: #e31d3b; height: 0.8em; width: 0.8em;" class="ml-1 d-inline-block v-align-middle Box border-black-fade"></span></code>.
=>  Changed "View profile" button style

index.html
Added Google Groups link in the social media section.
- [Preview Link](https://sahilsaha7773.github.io/gci18.fossasia.org/)
- Fixes #466 
Added Google Groups link.
=> Added Google groups link

index.html
- [Preview Link](https://sahilsaha7773.github.io/gci18.fossasia.org/)
- Fixes #450 
Added Gitter link.
=> Added Gitter link

index.html, js/custom.js
- [Preview Link](https://niteshkumarniranjan.github.io/gci18.fossasia.org/)
- Fixes #471 
Merge two jQuery defination in one and moved script from index.html to custom.js
=> Merge two jQuery defination in one (#471)

CNAME, js/thankyou.js
Reverts fossasia/gci18.fossasia.org#441
=> Revert "Added Thank you for contributing in Malayalam "

index.html
- [Preview Link](https://pythongiant.github.io/gci18.fossasia.org/)
- Fixes #481 
Add social media icons
=> add social media icons

_includes/footer.html, index.html
=> Add VK in social media and add the missing social links in footer

index.html
Removing the extra classes which are overlapping the past .fa class
i have checked everything with that everything is working fine all.css does not require and if require it should be placed properly 
according to me it's working fine without that class
preview link : http://niec.ml/
- Fixes  #492
removal  of extra all.css class which was overwriting the other classes
=> Fixed the social media icons 

css/custom.css
- Fixes #443 
The z-index of leaflet was more than the z-index of navbar . So , I changed that.
=> Fix map bottom leaflet 

_includes/header-pages.html, _includes/header.html
- Fixes #454 
Removed Google translate and the language list in students_projects.html navbar, as there were of no use without functionality .
=> Remove google translate

css/_custom.scss, index.html
- [Preview Link](https://saarthakchats.github.io/op/)
- Fixes #513 
Fixed image position and look in the Welcome section, check issue #513 for details
=> (#513)Fixed image and look on the welcome section

index.html
- added more displays to the social media section
- [Preview](https://ngmhprogramming.github.io/gci18.fossasia.org/)
- added flickr photo slideshow
- added google+ badge
- added github profile card
=> added more social media displays

_data/mentors.yml
- [Preview Link](https://sahilsaha7773.github.io/gci18.fossasia.org)
- Fixes #527 
Added a mentor's location in the map.
=> Added a mentor's location

_data/mentors.yml
- [Preview Link]https://nishithp2004.github.io/gci18.fossasia.org
Hi have added the geolocation of Jogendra Kumar 
=> Added location of a Mentor 

_data/mentors.yml
- [Preview Link](https://shreeshjha.github.io/gci18.fossasia.org/.)
Added Akshat Jain's Location in the following page.
=> Added mentors location(Akshat Jain)

_data/mentors.yml
- [Preview Link](https://niteshkumarniranjan.github.io/gci18.fossasia.org/)
Added Mentor(abhisekvashok) Location
=> Added Mentor(abhisekvashok) Location

_includes/header-pages.html, students_projects.html
- [Preview Link](https://applec4t.github.io/gci18.fossasia.org/students_projects.html)
- Fixes #533 
Fixed the Student Projects page by changing the `header-pages.html` file included in the page's layout.
=> Fixes #533: Fixed the Student Projects page

README.md
Link to the website replaced with markdown link
=> Link to the website replaced with markdown link

css/_custom.scss
- [Preview Link](https://niteshkumarniranjan.github.io/gci18.fossasia.org/)
- Fixes #530 
Fixed Header Z-index (#530)
=> Fixed Header Z-index (#530)

README.md
- Fixes #545 
- Added documentation and tutorials describing the Videos and Map section to the README file.
=> Updated the README file (#545)

js/thankyou.js
Signed-off-by: Mohan Cm <mohanmanjappa@gmail.com>
- [Preview Link](https://github.com/mohancm/gci18.fossasia.org/blob/master/js/thankyou.js#L33)
- changes - Added Latin Translation
Added Latin translation for 'Thank you for your contributions!' in thankyou.js
Screenshots if any:
- > Before:
- > After:
=> thankyou.js: Add Latin Translation

js/thankyou.js
Signed-off-by: Mohan Cm <mohanmanjappa@gmail.com>
- [x ] Included a description of the change below.
- [Preview Link](url)
Corrected kannada translation
=> thankyou.js: Correct Kannada Translation

_includes/load-videos.html, css/ytload.css, index.html
- [Preview Link](https://applec4t.github.io/gci18.fossasia.org/)
- Fixes #547 
While locally testing the recently added script in the video section I noticed that when adding more videos the loop brakes and the videos don't display. This is a quick hotfix to ensure that more videos can be added in the future.
Main changes:
- fixed the jekyll bug, ensuring that the section can handle multiple videos
- changed the alignment of videos (the videos now align like the mentors/students cards in order to achieve responsibility)
Trying to add more videos:
Current section with one video:
Example of multiple videos:
=> Hotfix: YouTube API in the video section (#547)

_data/projects.yml
- [Preview Link](https://shreeshjha.github.io/gci18.fossasia.org/students_projects.html)
I added my personal portfolio on student projects.
=> Added a Student Project

js/thankyou.js
- [https://github.com/AshwanthKumar7230/gci18.fossasia.org/blob/master/js/thankyou.js ] Included a Preview link and screenshot showing after and before the changes.
- [ Added 'Thank you for contributing' in arabic.] Included a description of the change below.
- [Preview Link](https://github.com/AshwanthKumar7230/gci18.fossasia.org/blob/master/js/thankyou.js)
- Fixes #<20>
Added 'Thank you for contributing' in arabic.
=> Added 'Thank you for contributing' in arabic.

index.html
- [Preview Link](https://ycwei982.github.io/gci18.fossasia.org/#students)
- Fixes fossasia#479
Change `{% for student in site.data.students limit:30 %}` to `{% for student in site.data.students %}` in `index.html`.
p.s. I need to fix this before adding my profile picture to this website
=> Fix #479 student not shown

js/thankyou.js
- [Preview Link](https://github.com/fossasia/gci18.fossasia.org/blob/97c4193b6e41628f7d15c708b856da3a89e8e260/js/thankyou.js)
Added a line in `./js/thankyou.js`
=> Add "Thank you for your contributions!" in Japanese

_includes/footer.html, js/image-fadein.js
- [Preview Link](https://myfrom.github.io/gci18.fossasia.org/)
- Fixes #567
Added a fade-in effect to images. This is a progressive enhancement, very lightweight and doesn't break things in older browsers.
The images will be hidden until they enter the viewport.
Can't be shown on screenshots
=> Add fade-in effect to images

_includes/footer.html, _includes/header.html, _includes/load-videos.html
- [Preview Link](https://applec4t.github.io/gci18.fossasia.org/)
- Fixes #587 
Changed the loading of scripts by moving them to the `head` tag and loading them asynchronously using the `defer` attribute. This slightly benefited the performance and loading times by speeding up the time it takes the page to become interactive and react to user's input.
The tests were done few times using Google Chrome's Audits on the following settings:
- Desktop device (no emulations)
- No throttling 
- Clear memory before auditing 
By trying to access the page from mobile I also noticed a slight improvement in input latency.
=> (#587) Improved performance by adding defer asynchronous script loading

js/thankyou.js
- [Preview Link](https://ksninja.github.io/gci18.fossasia.org)
- Fixes #606
=> Add turkish language in thanking contributors section

_includes/footer.html, index.html
- [Preview link]https://nishithp2004.github.io/gci18.fossasia.org
- Fixes #598 
Hi I have replaced Slack with Gitter
=> Removed slack

_data/mentors.yml
- [Preview Link](https://github.com/ksninja/gci18.fossasia.org)
- Fixes #283 
=> Add mentor's (Saurav Vishal's) coordinates for map section

_data/mentors.yml
- [*] Included a Preview link.
- [*] Included a description of the change below.
Updated mentors details by appending coordinates for @meets2tarun.   
- [Preview Link](https://github.com/pranavkrish04/gci18.fossasia.org)
- Fixes #283 
Geolocation of @meets2tarun is added.
`  lat: 25.540956712303636
lng: 84.85105172962317`
=> Update mentors.yml with Mentor's co-ordinates

_includes/header.html, css/_custom.scss, js/navigationbar.js
- Fixes #623 
Added auto hide feature to nav bar . It hides based on user's scroll actions .
=> Add autohide feature to navigation bar (#623)

css/_custom.scss
- Fixes #626 
Changed the color of back to top button to match the theme design .
=> Change color of backto top btn to match theme (#626)

index.html
- [Preview Link](https://sahilsaha7773.github.io/gci18.fossasia.org/)
- Fixes #632 
Added animation to the first slider's text to make it more attractive.
=> Added animation to the first slider's text

index.html
- [Preview Link](https://nishithp2004.github.io/gci18.fossasia.org)
- Fixes #645 
Hi I have added Winners , Finalists and Contributors section to the site.
***Please note that the Winners,Finalists and Contributors are yet to be added as they are not announced yet.***
=> Added Winners,Finalists and Contributors section 
